name = "lawfirm-site"
compatibility_date = "2024-01-01"

[env.production]
pages_build_output_dir = "public"

# Database configuration (update database_id after creating D1 database)
[[env.production.d1_databases]]
binding = "DB"
database_name = "lawfirm-db"
database_id = "YOUR_DATABASE_ID_HERE"  # Replace with actual ID from: wrangler d1 create lawfirm-db

# Environment variables (set these in Cloudflare dashboard)
[env.production.vars]
# These will be overridden by dashboard settings
FIRM_EMAIL = "info@sharmaassociates.co.in"
ADMIN_USERNAME = "admin" 